### ISSUE TITLE
Update to latest

### ISSUE THREAD

**Issue by jbeacham** [Wenfengcheng/AMScrollingNavbar_Xamarin.iOS#1]
@Wenfengcheng Thanks for the port! Any plans to update to the latest with all their bug fixes?

**Comment by Wenfengcheng** [comment]
@jbeacham  Sorry, I no longer do xamarin related development, maybe you can refer to this [walkthrough](https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough) to complete the binding.
